version: 2.1

orbs:
  ruby: circleci/ruby@1.0
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.3-node
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"

  rspec:
    docker:
      - image: cimg/ruby:3.0.3-node
        environment:
          RAILS_ENV: test
          DB_USERNAME: postgres
          DB_PASSWORD: postgres

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: finance_test
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database setup
          command: bundle exec rails db:schema:load --trace
      - run:
          name: Rspec
          command: bundle exec rspec

  rubocop:
    docker:
      - image: cimg/ruby:3.0.3-node
        environment:
          RAILS_ENV: test
          DB_USERNAME: postgres
          DB_PASSWORD: postgres

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: finance_test
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: rubocop
          command: bundle exec rubocop

  rails_best_practices:
    docker:
      - image: cimg/ruby:3.0.3-node
        environment:
          RAILS_ENV: test
          DB_USERNAME: postgres
          DB_PASSWORD: postgres

      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: finance_test
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: rails_best_practices
          command: bundle exec rails_best_practices

workflows:
  build_and_test:
    jobs:
      - build
      - rspec:
          requires:
            - build
      - rubocop:
          requires:
            - build
      - rails_best_practices:
          requires:
            - build
